  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Talks"
  weight = 200
  identifier = "talks"
  url = "/talks/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[footer]]
  name = "Powered by the Anatole Hugo Theme"
  weight = 1
  identifier = "https://github.com/lxndrblz/anatole"
  url = "https://github.com/lxndrblz/anatole"
